---

env: "local" # dev, prod
host: "0.0.0.0"

grpc:
  port: 5463
  timeout: 5s
  type: tcp

http:
  port: 5462
  read_timeout: 4s
  write_timeout: 4s
  cors:
    debug: true
    allowed_methods:
      - "GET"
      - "HEAD"
      - "POST"
      - "PATCH"
      - "PUT"
      - "OPTIONS"
      - "DELETE"
    allowed_origins:
      - "*"
    allow_credentials: true
    allowed_headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options_passthrough: false
    exposed_headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"

db:
  max_attempts: 5
  max_delay: 5s
  migration_path: "./migrations"
  sqlite:
    storage_path: "./storage/sso_grpc.db"
    migration_table: "migrations"
  pgsql:
    username: "root"
    password: "password"
    database: "sso"
    port: 5432
    attempts: 5
    host: "postgres"
    sslmode: "disable"

token:
  ttl: 20m
  refresh: 72h
  secret: "2baf1d115376UCi6hvKCpM"
  secret_refresh: "Y2Vzc19pZCI6Ijk2ZDg4MDM4MjMyQ1MWUxZjkzMDZiMTgwZmFhNzc4YmFmMT"

appConfig:
  log_level: "trace"
  log_json: false

metrics:
  port: 5464

queue:
  driver: "amqp"
  host: "rabbitmq"
  port: 5672
  user: "admin"
  pass: "password"
  max_attempts: 5
  max_delay: 5s